/**
 * Testnet setup script.
 * Generates three keypairs, funds them via Friendbot,
 * creates a trustline, and issues ANCH tokens.
 * Run once: node scripts/setup-testnet.mjs
 */

import { Keypair, Networks, Horizon, TransactionBuilder, BASE_FEE, Operation, Asset } from '@stellar/stellar-sdk';
import { writeFileSync, existsSync } from 'fs';

const ASSET_CODE = 'ANCH';
const ASSET_SUPPLY = '1000000';
const HORIZON_URL = 'https://horizon-testnet.stellar.org';
const FRIENDBOT_URL = 'https://friendbot.stellar.org';
const NETWORK_PASSPHRASE = Networks.TESTNET;

const server = new Horizon.Server(HORIZON_URL);

// Safety guard — prevent accidental re-run which would generate new keys
if (existsSync('.env.testnet')) {
  console.error('ERROR: .env.testnet already exists. Delete it manually if you want to reset.');
  process.exit(1);
}

console.log('=== Stellar Anchor — Testnet Setup ===\n');

// --- Step 1: Generate keypairs ---
console.log('Step 1: Generating keypairs...');
const issuer = Keypair.random();
const distribution = Keypair.random();
const signing = Keypair.random();

console.log(`  Issuer:       ${issuer.publicKey()}`);
console.log(`  Distribution: ${distribution.publicKey()}`);
console.log(`  Signing:      ${signing.publicKey()}`);

// --- Step 2: Fund via Friendbot ---
console.log('\nStep 2: Funding accounts via Friendbot...');

async function fundAccount(keypair, label) {
  const res = await fetch(`${FRIENDBOT_URL}?addr=${keypair.publicKey()}`);
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Friendbot failed for ${label}: ${body}`);
  }
  console.log(`  Funded ${label}: ${keypair.publicKey()}`);
}

await fundAccount(issuer, 'issuer');
await fundAccount(distribution, 'distribution');
await fundAccount(signing, 'signing');

// Give the ledger a moment to confirm
console.log('\n  Waiting for ledger confirmation...');
await new Promise(r => setTimeout(r, 5000));

// --- Step 3: Create trustline (distribution trusts issuer for ANCH) ---
console.log('\nStep 3: Creating trustline (distribution → ANCH)...');

const asset = new Asset(ASSET_CODE, issuer.publicKey());
const distAccount = await server.loadAccount(distribution.publicKey());

const trustlineTx = new TransactionBuilder(distAccount, {
  fee: BASE_FEE,
  networkPassphrase: NETWORK_PASSPHRASE,
})
  .addOperation(Operation.changeTrust({
    asset,
    limit: '10000000',
  }))
  .setTimeout(30)
  .build();

trustlineTx.sign(distribution);
await server.submitTransaction(trustlineTx);
console.log(`  Trustline created: distribution trusts ${ASSET_CODE} from issuer`);

// --- Step 4: Issue tokens (issuer → distribution) ---
console.log(`\nStep 4: Issuing ${ASSET_SUPPLY} ${ASSET_CODE} to distribution account...`);

const issuerAccount = await server.loadAccount(issuer.publicKey());

const issueTx = new TransactionBuilder(issuerAccount, {
  fee: BASE_FEE,
  networkPassphrase: NETWORK_PASSPHRASE,
})
  .addOperation(Operation.payment({
    destination: distribution.publicKey(),
    asset,
    amount: ASSET_SUPPLY,
  }))
  .setTimeout(30)
  .build();

issueTx.sign(issuer);
await server.submitTransaction(issueTx);
console.log(`  Issued ${ASSET_SUPPLY} ${ASSET_CODE} to distribution account`);

// --- Step 5: Save keypairs to .env.testnet ---
console.log('\nStep 5: Saving keypairs to .env.testnet...');

const env = [
  '# Stellar Anchor — Testnet Keypairs',
  '# Generated by scripts/setup-testnet.mjs',
  '# NEVER commit this file. It is in .gitignore.',
  '',
  `ASSET_CODE=${ASSET_CODE}`,
  `ASSET_ISSUER_PUBLIC=${issuer.publicKey()}`,
  `ASSET_ISSUER_SECRET=${issuer.secret()}`,
  '',
  `DISTRIBUTION_PUBLIC=${distribution.publicKey()}`,
  `DISTRIBUTION_SECRET=${distribution.secret()}`,
  '',
  `SIGNING_PUBLIC=${signing.publicKey()}`,
  `SIGNING_SECRET=${signing.secret()}`,
  '',
  `HORIZON_URL=${HORIZON_URL}`,
  `NETWORK_PASSPHRASE="${NETWORK_PASSPHRASE}"`,
  '',
].join('\n');

writeFileSync('.env.testnet', env, { mode: 0o600 });
console.log('  Written: .env.testnet (permissions: 600)');

// --- Step 6: Verify balances ---
console.log('\nStep 6: Verifying final balances...\n');

async function printBalances(keypair, label) {
  const account = await server.loadAccount(keypair.publicKey());
  console.log(`  ${label} (${keypair.publicKey().slice(0, 8)}...):`);
  account.balances.forEach(b => {
    const name = b.asset_type === 'native' ? 'XLM' : b.asset_code;
    console.log(`    ${name}: ${b.balance}`);
  });
}

await printBalances(issuer, 'Issuer');
await printBalances(distribution, 'Distribution');
await printBalances(signing, 'Signing');

console.log('\n=== Setup Complete ===');
console.log(`\nAsset: ${ASSET_CODE}:${issuer.publicKey()}`);
console.log(`Stellar Expert: https://stellar.expert/explorer/testnet/asset/${ASSET_CODE}-${issuer.publicKey()}`);
console.log('\nNext step: configure the Anchor Platform with these keys.');
