/**
 * Generates mainnet keypairs + all config files for the ANCH anchor.
 *
 * Run from project root:
 *   node scripts/setup-mainnet.mjs
 *
 * Outputs:
 *   .env.mainnet                          ← secrets (never commit)
 *   config/anchor-platform.mainnet.yaml  ← anchor platform config
 *   config/stellar.toml.mainnet          ← review and copy to stellar.toml
 *
 * After running:
 *   1. Fund the three accounts with XLM (see printed instructions)
 *   2. node scripts/init-mainnet-accounts.mjs   ← sets up trustlines + mints ANCH
 *   3. docker compose -f docker-compose.mainnet.yml up --build
 */

import { Keypair } from '@stellar/stellar-sdk';
import { randomBytes } from 'crypto';
import { writeFileSync, existsSync } from 'fs';

// ─── Safety check ─────────────────────────────────────────────────────────────

if (existsSync('.env.mainnet')) {
  console.log('⚠  .env.mainnet already exists. Delete it first if you want fresh keys.');
  process.exit(1);
}

// ─── Generate keypairs ────────────────────────────────────────────────────────

const signing      = Keypair.random();   // signs SEP-10 challenges
const distribution = Keypair.random();   // holds + disburses ANCH supply
const issuer       = Keypair.random();   // mints ANCH (set as asset issuer)

const rand = () => randomBytes(32).toString('hex');
const jwtSecret                = rand();
const sep24InteractiveSecret   = rand();
const sep24MoreInfoSecret      = rand();
const sep6MoreInfoSecret       = rand();
const platformApiSecret        = rand();

// ─── .env.mainnet ─────────────────────────────────────────────────────────────

const envContent = `# ANCH Anchor — Mainnet
# Generated by scripts/setup-mainnet.mjs  ${new Date().toISOString()}
# ⚠  KEEP PRIVATE — contains secret keys. Never commit this file.

ASSET_CODE=ANCH
HORIZON_URL=https://horizon.stellar.org
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

# SEP-10 signing keypair (proves you are the anchor)
SIGNING_PUBLIC=${signing.publicKey()}
SIGNING_SECRET=${signing.secret()}

# Distribution account (holds ANCH supply, pays out on deposit)
DISTRIBUTION_PUBLIC=${distribution.publicKey()}
DISTRIBUTION_SECRET=${distribution.secret()}

# Asset issuer (creates ANCH; set AUTHORIZATION_REQUIRED flag after setup)
ASSET_ISSUER_PUBLIC=${issuer.publicKey()}
ASSET_ISSUER_SECRET=${issuer.secret()}

# JWT secrets
SEP10_JWT_SECRET=${jwtSecret}
SEP24_INTERACTIVE_JWT_SECRET=${sep24InteractiveSecret}
SEP24_MORE_INFO_JWT_SECRET=${sep24MoreInfoSecret}
SEP6_MORE_INFO_JWT_SECRET=${sep6MoreInfoSecret}
PLATFORM_API_SECRET=${platformApiSecret}
`;

writeFileSync('.env.mainnet', envContent, { mode: 0o600 });
console.log('✓ .env.mainnet written (permissions 600)');

// ─── anchor-platform.mainnet.yaml ─────────────────────────────────────────────

const platformYaml = `# Anchor Platform — Mainnet
# Generated by scripts/setup-mainnet.mjs

version: 1

stellar_network:
  network: MAINNET
  horizon_url: https://horizon.stellar.org
  type: horizon

callback_api:
  base_url: http://business-server:3000
  auth:
    type: none

platform_api:
  auth:
    type: none

app_logging:
  level: INFO
  stellar_level: INFO

sep1:
  enabled: true
  toml:
    type: file
    value: /config/stellar.toml

sep10:
  enabled: true
  home_domains:
    - localhost:8080   # ← replace with your real domain in production

sep12:
  enabled: true

sep24:
  enabled: true
  interactive_url:
    base_url: http://localhost:3000/sep24/interactive
    jwt_expiration: 3600
  more_info_url:
    base_url: http://localhost:3000/sep24/transaction
    jwt_expiration: 3600

sep6:
  enabled: true
  features:
    account_creation: false
    claimable_balances: false
  more_info_url:
    base_url: http://localhost:3000/sep6/transaction
    jwt_expiration: 3600

sep31:
  enabled: true
  payment_type: STRICT_SEND

sep38:
  enabled: true
  sep10_enforced: false
  auth_enforced: false

data:
  type: postgres
  server: db:5432
  database: anchordb
  flyway_enabled: true
  ddl_auto: update

events:
  enabled: false

assets:
  type: yaml
  value: |
    items:
      - id: "stellar:ANCH:${issuer.publicKey()}"
        distribution_account: "${distribution.publicKey()}"
        significant_decimals: 2
        sep24:
          enabled: true
          deposit:
            enabled: true
            min_amount: 1
            max_amount: 1000000
            methods:
              - WIRE
          withdraw:
            enabled: true
            min_amount: 1
            max_amount: 1000000
            methods:
              - WIRE
`;

writeFileSync('config/anchor-platform.mainnet.yaml', platformYaml);
console.log('✓ config/anchor-platform.mainnet.yaml written');

// ─── stellar.toml.mainnet ──────────────────────────────────────────────────────

const tomlContent = `NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
TRANSFER_SERVER_SEP0024="https://YOUR_DOMAIN/sep24"
WEB_AUTH_ENDPOINT="https://YOUR_DOMAIN/auth"
SIGNING_KEY="${signing.publicKey()}"

[DOCUMENTATION]
ORG_NAME="Your Anchor Name"
ORG_URL="https://YOUR_DOMAIN"
ORG_DESCRIPTION="Stellar anchor for ANCH"

[[CURRENCIES]]
code="ANCH"
issuer="${issuer.publicKey()}"
status="live"
name="Anchor Token"
desc="Token issued by the ANCH anchor"
is_asset_anchored=false
anchor_asset_type="fiat"
display_decimals=2
`;

writeFileSync('config/stellar.toml.mainnet', tomlContent);
console.log('✓ config/stellar.toml.mainnet written (review + copy to stellar.toml before starting)');

// ─── Instructions ──────────────────────────────────────────────────────────────

console.log(`
╔══════════════════════════════════════════════════════════════════╗
║              MAINNET SETUP — NEXT STEPS                          ║
╠══════════════════════════════════════════════════════════════════╣
║                                                                  ║
║  Fund these 3 accounts with XLM on Stellar mainnet:             ║
║  (send at least 3 XLM to each — needed for reserves + fees)     ║
║                                                                  ║
║  SIGNING account:                                                ║
║  ${signing.publicKey()}   ║
║                                                                  ║
║  DISTRIBUTION account:                                           ║
║  ${distribution.publicKey()}   ║
║                                                                  ║
║  ISSUER account:                                                 ║
║  ${issuer.publicKey()}   ║
║                                                                  ║
║  After funding all 3, run:                                       ║
║    node scripts/init-mainnet-accounts.mjs                        ║
║                                                                  ║
║  That script will:                                               ║
║    - Distribution creates ANCH trustline to Issuer              ║
║    - Issuer mints 1,000,000 ANCH → Distribution                 ║
║                                                                  ║
║  Then start the mainnet stack:                                   ║
║    docker compose -f docker-compose.mainnet.yml up --build       ║
╚══════════════════════════════════════════════════════════════════╝
`);
